language: ruby
notifications:
  email:
    - melevir@gmail.com
script: bundle
env:
#  - DB=sqlite3
#  - DB=sqlite3mem
#  - DB=postgresql
  - DB=mysql
rvm:
#  - 2.0.0
  - 1.9.3
before_script:
  - git clone -b 2.3-stable git://github.com/redmine/redmine.git redmine
  - ln -s ../../ redmine/plugins/phabmine
  - ls redmine
  - ls redmine/plugins
  - ls redmine/plugins/phabmine
  - ls  redmine/plugins/phabmine/test
script:
  - rake prepare
  - rake test