language: ruby
notifications:
  email:
    - melevir@gmail.com
script: bundle
env:
#  - DB=sqlite3
#  - DB=sqlite3mem
#  - DB=postgresql
  - DB=mysql
rvm:
  - 2.0.0
  - 1.9.3
before_script:
  - git clone -b 2.2-stable git://github.com/redmine/redmine.git redmine
  - ls redmine
  - ln -s ../phabmine redmine/plugins/phabmine
  - ls redmine/plugins/
script:
  - rake test