language: ruby
notifications:
  email:
    - melevir@gmail.com
script: bundle
env:
  - DB=sqlite3
#  - DB=sqlite3mem
#  - DB=postgresql
rvm:
#  - 2.0.0
  - 1.9.3
before_script:
  - git clone -b 2.3-stable git://github.com/redmine/redmine.git redmine
  - git clone https://github.com/Melevir/ruby-phabricator.git
  - ln -s ../../ redmine/plugins/phabmine
  - cd redmine/
script:
  - rake -f ../Rakefile prepare RAILS_ENV=test
  - rake redmine:plugins:test PLUGIN=phabmine RAILS_ENV=test