language: ruby
notifications:
  email:
    - melevir@gmail.com
script: bundle
env:
  - DB=sqlite3
  - DB=sqlite3mem
  - DB=postgresql
  - DB=mysql
rvm:
  - 2.0.0
  - 1.9.3
  - rbx-19mode
  - jruby-19mode
  - 1.8.7
  - rbx-18mode
  - jruby-18mode
